- name: Install nginx
  apt:
    name: nginx
    state: present
    update_cache: yes

- name: Deploy site config
  template:
    src: app.conf.j2
    dest: /etc/nginx/sites-available/app.conf
    owner: root
    group: root
    mode: '0644'
  notify: reload nginx

- name: Enable site
  file:
    src: /etc/nginx/sites-available/app.conf
    dest: /etc/nginx/sites-enabled/app.conf
    state: link
  notify: reload nginx

- name: Remove default site
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent
  notify: reload nginx

- name: Simple index page with host tag
  copy:
    dest: /var/www/html/index.html
    content: |
      <h1>{{ inventory_hostname }}</h1>
      <p>Deployed at {{ ansible_date_time.iso8601 }}</p>

- name: Ensure nginx running
  service:
    name: nginx
    state: started
    enabled: true

