name: CI
on:
  push:
    branches:
      - main
      - 'releases/**'
  pull_request:
    branches:
      - main

jobs:
  lint-and-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Ansible tooling
        run: |
          python -m pip install --upgrade pip
          pip install ansible ansible-lint yamllint

      - name: Yamllint
        run: yamllint .

      - name: Ansible-lint
        run: ansible-lint

      - name: Syntax check
        run: ansible-playbook -i inventory.ini site.yml --syntax-check

      - name: Dry run (no-op)
        run: ansible-playbook -i inventory.ini site.yml --check --diff || true
 
